### ISSUE TITLE
server not closing

### ISSUE THREAD

**Issue by ghost** [sveinnthorarins/Minecraft-Server-Management#1]
Hi,
The server doenst close after 30 minutes. It does say shutting down., but nothing happens

**Comment by sveinnthorarins** [comment]
Hey dude 🙂

Just want to start off saying, it's been more than 3 years since I wrote this little program, and I don't remember everything clearly. I wanted to publish it on GitHub so people could use it if they wanted, but I don't intend on making any changes/commits or providing quick or extensive support. I tested it on my server at the time for several months, so the program should work (although I should say I only tested it on Windows 7 and 10, not the new 11).

That being said, I remember that the program sends the stop message to the server via RCON. So make sure you configure your server (via the `server.properties` file) and enable RCON and set an RCON password.

If that doesn't fix it, you'll have to diagnose the problem yourself, maybe look into the code, debug, edit and build the program yourself. Thank you for showing interest in my little project though, makes me happy 😄

**Comment by contributemore** [comment]
This is the BEST solution I've found. **Actual saint.**
Just wish you could make the timeout faster. Something like 5 minutes of inactivity. 

-Never mind, just recompiled with "chrono::minutes sleepTime(5);" on line 73

Actual Saint

**Comment by sveinnthorarins** [comment]
@michaellatsky Thank you for the nice comment. I am glad you like it and that it's useful to you.

**Comment by sveinnthorarins** [comment]
I'm closing this issue since sufficient guidance has been provided and the original poster hasn't requested further help for a while.
